# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20160905_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
