# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(choices=[('STUDY', 'Project As Student'), ('WORK', 'Project From Work'), ('LIFE', 'Project From Life')], default='LIFE', max_length=10),
            preserve_default=False,
        ),
    ]
