# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.CharField(choices=[('STUDY', '\u4e0a\u5b66\u671f\u95f4\u9879\u76ee'), ('WORK', '\u5de5\u4f5c\u76f8\u5173\u9879\u76ee'), ('LIFE', '\u4e1a\u4f59\u65f6\u95f4\u9879\u76ee')], max_length=10),
        ),
    ]
